"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.training import Training
globals()['Training'] = Training
from osis_education_group_sdk.model.paginated_training_all_of import PaginatedTrainingAllOf


class TestPaginatedTrainingAllOf(unittest.TestCase):
    """PaginatedTrainingAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedTrainingAllOf(self):
        """Test PaginatedTrainingAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedTrainingAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
