"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.09
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.active_enum import ActiveEnum


class TestActiveEnum(unittest.TestCase):
    """ActiveEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActiveEnum(self):
        """Test ActiveEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActiveEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
