"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.09
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.constraint_type_enum import ConstraintTypeEnum
from osis_education_group_sdk.model.node import Node
from osis_education_group_sdk.model.node_sub_type_enum import NodeSubTypeEnum
from osis_education_group_sdk.model.node_type_enum import NodeTypeEnum
globals()['ConstraintTypeEnum'] = ConstraintTypeEnum
globals()['Node'] = Node
globals()['NodeSubTypeEnum'] = NodeSubTypeEnum
globals()['NodeTypeEnum'] = NodeTypeEnum
from osis_education_group_sdk.model.tree import Tree


class TestTree(unittest.TestCase):
    """Tree unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTree(self):
        """Test Tree"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tree()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
