"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.print_orientation_enum import PrintOrientationEnum


class TestPrintOrientationEnum(unittest.TestCase):
    """PrintOrientationEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPrintOrientationEnum(self):
        """Test PrintOrientationEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PrintOrientationEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
