"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.node_type_enum import NodeTypeEnum


class TestNodeTypeEnum(unittest.TestCase):
    """NodeTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeTypeEnum(self):
        """Test NodeTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodeTypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
