"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.active_enum import ActiveEnum
from osis_education_group_sdk.model.array_of_versions import ArrayOfVersions
from osis_education_group_sdk.model.campus import Campus
from osis_education_group_sdk.model.constraint_type_enum import ConstraintTypeEnum
from osis_education_group_sdk.model.schedule_type_enum import ScheduleTypeEnum
globals()['ActiveEnum'] = ActiveEnum
globals()['ArrayOfVersions'] = ArrayOfVersions
globals()['Campus'] = Campus
globals()['ConstraintTypeEnum'] = ConstraintTypeEnum
globals()['ScheduleTypeEnum'] = ScheduleTypeEnum
from osis_education_group_sdk.model.mini_training_detailed_all_of import MiniTrainingDetailedAllOf


class TestMiniTrainingDetailedAllOf(unittest.TestCase):
    """MiniTrainingDetailedAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMiniTrainingDetailedAllOf(self):
        """Test MiniTrainingDetailedAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MiniTrainingDetailedAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
