"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.10
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.mini_training_type_enum import MiniTrainingTypeEnum
globals()['MiniTrainingTypeEnum'] = MiniTrainingTypeEnum
from osis_education_group_sdk.model.mini_training import MiniTraining


class TestMiniTraining(unittest.TestCase):
    """MiniTraining unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMiniTraining(self):
        """Test MiniTraining"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MiniTraining()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
