"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_education_group_sdk
from osis_education_group_sdk.api.mini_trainings_api import MiniTrainingsApi  # noqa: E501


class TestMiniTrainingsApi(unittest.TestCase):
    """MiniTrainingsApi unit test stubs"""

    def setUp(self):
        self.api = MiniTrainingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_mini_training_prerequisites_official(self):
        """Test case for mini_training_prerequisites_official

        """
        pass

    def test_mini_training_version(self):
        """Test case for mini_training_version

        """
        pass

    def test_minitraining_tree(self):
        """Test case for minitraining_tree

        """
        pass

    def test_minitraining_version_tree(self):
        """Test case for minitraining_version_tree

        """
        pass

    def test_minitrainings_list(self):
        """Test case for minitrainings_list

        """
        pass

    def test_minitrainings_offer_roots(self):
        """Test case for minitrainings_offer_roots

        """
        pass

    def test_minitrainings_read(self):
        """Test case for minitrainings_read

        """
        pass

    def test_minitrainings_title_version_read(self):
        """Test case for minitrainings_title_version_read

        """
        pass

    def test_minitrainingstitle_read(self):
        """Test case for minitrainingstitle_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
