"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.10
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_education_group_sdk
from osis_education_group_sdk.api.groups_api import GroupsApi  # noqa: E501


class TestGroupsApi(unittest.TestCase):
    """GroupsApi unit test stubs"""

    def setUp(self):
        self.api = GroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_groups_read(self):
        """Test case for groups_read

        """
        pass

    def test_groups_tree(self):
        """Test case for groups_tree

        """
        pass

    def test_groupstitle_read(self):
        """Test case for groupstitle_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
