"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.08
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_education_group_sdk
from osis_education_group_sdk.api.trainings_api import TrainingsApi  # noqa: E501


class TestTrainingsApi(unittest.TestCase):
    """TrainingsApi unit test stubs"""

    def setUp(self):
        self.api = TrainingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_training_prerequisites_official(self):
        """Test case for training_prerequisites_official

        """
        pass

    def test_training_version(self):
        """Test case for training_version

        """
        pass

    def test_trainings_list(self):
        """Test case for trainings_list

        """
        pass

    def test_trainings_offer_roots(self):
        """Test case for trainings_offer_roots

        """
        pass

    def test_trainings_read(self):
        """Test case for trainings_read

        """
        pass

    def test_trainings_tree(self):
        """Test case for trainings_tree

        """
        pass

    def test_trainingstitle_read(self):
        """Test case for trainingstitle_read

        """
        pass

    def test_trainingsversiontitle_read(self):
        """Test case for trainingsversiontitle_read

        """
        pass

    def test_versions_tree(self):
        """Test case for versions_tree

        """
        pass


if __name__ == '__main__':
    unittest.main()
