"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.08
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.training_type_enum import TrainingTypeEnum
globals()['TrainingTypeEnum'] = TrainingTypeEnum
from osis_education_group_sdk.model.training import Training


class TestTraining(unittest.TestCase):
    """Training unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTraining(self):
        """Test Training"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Training()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
