"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.08
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.academic_type_enum import AcademicTypeEnum
from osis_education_group_sdk.model.active_enum import ActiveEnum
from osis_education_group_sdk.model.activity_presence_enum import ActivityPresenceEnum
from osis_education_group_sdk.model.array_of_versions import ArrayOfVersions
from osis_education_group_sdk.model.campus import Campus
from osis_education_group_sdk.model.constraint_type_enum import ConstraintTypeEnum
from osis_education_group_sdk.model.decree_category_enum import DecreeCategoryEnum
from osis_education_group_sdk.model.duration_unit_enum import DurationUnitEnum
from osis_education_group_sdk.model.internship_presence_enum import InternshipPresenceEnum
from osis_education_group_sdk.model.print_orientation_enum import PrintOrientationEnum
from osis_education_group_sdk.model.rate_code_enum import RateCodeEnum
from osis_education_group_sdk.model.schedule_type_enum import ScheduleTypeEnum
from osis_education_group_sdk.model.training import Training
from osis_education_group_sdk.model.training_detailed_all_of import TrainingDetailedAllOf
from osis_education_group_sdk.model.training_type_enum import TrainingTypeEnum
globals()['AcademicTypeEnum'] = AcademicTypeEnum
globals()['ActiveEnum'] = ActiveEnum
globals()['ActivityPresenceEnum'] = ActivityPresenceEnum
globals()['ArrayOfVersions'] = ArrayOfVersions
globals()['Campus'] = Campus
globals()['ConstraintTypeEnum'] = ConstraintTypeEnum
globals()['DecreeCategoryEnum'] = DecreeCategoryEnum
globals()['DurationUnitEnum'] = DurationUnitEnum
globals()['InternshipPresenceEnum'] = InternshipPresenceEnum
globals()['PrintOrientationEnum'] = PrintOrientationEnum
globals()['RateCodeEnum'] = RateCodeEnum
globals()['ScheduleTypeEnum'] = ScheduleTypeEnum
globals()['Training'] = Training
globals()['TrainingDetailedAllOf'] = TrainingDetailedAllOf
globals()['TrainingTypeEnum'] = TrainingTypeEnum
from osis_education_group_sdk.model.training_detailed import TrainingDetailed


class TestTrainingDetailed(unittest.TestCase):
    """TrainingDetailed unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTrainingDetailed(self):
        """Test TrainingDetailed"""
        # FIXME: construct object with mandatory attributes with example values
        # model = TrainingDetailed()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
