"""
    Education Group Service

    A set of API endpoints that allow you to get, update, delete an education group.  # noqa: E501

    The version of the OpenAPI document: 1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_education_group_sdk
from osis_education_group_sdk.model.group_type_enum import GroupTypeEnum
from osis_education_group_sdk.model.learning_unit_type_enum import LearningUnitTypeEnum
from osis_education_group_sdk.model.mini_training_type_enum import MiniTrainingTypeEnum
from osis_education_group_sdk.model.training_type_enum import TrainingTypeEnum
globals()['GroupTypeEnum'] = GroupTypeEnum
globals()['LearningUnitTypeEnum'] = LearningUnitTypeEnum
globals()['MiniTrainingTypeEnum'] = MiniTrainingTypeEnum
globals()['TrainingTypeEnum'] = TrainingTypeEnum
from osis_education_group_sdk.model.node_sub_type_enum import NodeSubTypeEnum


class TestNodeSubTypeEnum(unittest.TestCase):
    """NodeSubTypeEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNodeSubTypeEnum(self):
        """Test NodeSubTypeEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = NodeSubTypeEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
